== 4.1

We'd like to thank to the following contributors from our
open source community that appear in this release notes
document:

@TomaszGaweda

@caioguedes

@SapnaDerajeRadhakrishna

Thank you for your valuable contributions!

[[features-41]]
=== New Features

* [jms, jdbc] Added exactly-once guarantee for JMS and JDBC sinks.
https://github.com/hazelcast/hazelcast-jet/pull/1813[#1813]
* [core] The `JobConfig.addClass()` method now automatically adds
the nested classes to the job.
https://github.com/hazelcast/hazelcast-jet/pull/1932[#1932]
* [core] The `JobConfig.addPackage()` now adds a whole Java package to
the job.
https://github.com/hazelcast/hazelcast-jet/pull/1932[#1932],
https://github.com/hazelcast/hazelcast-jet/pull/2077[#2077]
* [core] Added job-scoped serializer deployment options.
https://github.com/hazelcast/hazelcast-jet/pull/2020[#2020],
https://github.com/hazelcast/hazelcast-jet/pull/2038[#2038],
https://github.com/hazelcast/hazelcast-jet/pull/2039[#2039],
https://github.com/hazelcast/hazelcast-jet/pull/2043[#2043],
https://github.com/hazelcast/hazelcast-jet/pull/2071[#2071],
https://github.com/hazelcast/hazelcast-jet/pull/2075[#2075],
https://github.com/hazelcast/hazelcast-jet/pull/2082[#2082],
https://github.com/hazelcast/hazelcast-jet/pull/2190[#2190]
* [core] https://github.com/hazelcast/hazelcast-jet/blob/4.1/site/docs/design-docs/006-declarative-serialization.md[[006]] Added Protobuf serializer support.
https://github.com/hazelcast/hazelcast-jet/pull/2100[#2100]
* [pipeline-api] https://github.com/hazelcast/hazelcast-jet/blob/4.1/site/docs/design-docs/007-grpc-support.md[[007]] Added gRPC support for `mapUsingService`.
https://github.com/hazelcast/hazelcast-jet/pull/2095[#2095],
https://github.com/hazelcast/hazelcast-jet/pull/2185[#2185]

[[enh-41]]
=== Enhancements

* [jet-cli] Default logger has been changed from log4j to log4j2.
https://github.com/hazelcast/hazelcast-jet/pull/1981[#1981]
* [jet-cli] Simplified the default log output.
https://github.com/hazelcast/hazelcast-jet/pull/2047[#2047]
* [core] Improved the error message when a serializer is not registered.
https://github.com/hazelcast/hazelcast-jet/pull/2061[#2061]
* [integration] Added the Hazelcast Azure cluster self-discovery plugin to the
Jet distribution JAR.
https://github.com/hazelcast/hazelcast-jet/pull/2079[#2079]
* [pipeline-api] Added support for inner hash join.
@ omaszGaweda, https://github.com/hazelcast/hazelcast-jet/pull/2089[#2089]
* [core] When Jet starts up, it now logs the cluster name.
@caioguedes, https://github.com/hazelcast/hazelcast-jet/pull/2105[#2105]
* [core] Improved the error message when trying to deploy a JDK class
with `JobConfig`.
https://github.com/hazelcast/hazelcast-jet/pull/2108[#2108]
* [core] Implemented `JobConfig.toString()`.
@SapnaDerajeRadhakrishna, https://github.com/hazelcast/hazelcast-jet/pull/2152[#2152]
* [core] `Observable`, now, is not destroyed on shutdown.
https://github.com/hazelcast/hazelcast-jet/pull/2170[#2170]

[[fixes-41]]
=== Fixes

* [core] Fixed an issue where the interrupt signal was being sent to
blocking threads when a job is terminating.
https://github.com/hazelcast/hazelcast-jet/pull/1971[#1971]
* [core] Fixed an issue where the XML was picked over YAML when locating
the config file using working directory or classpath.
https://github.com/hazelcast/hazelcast-jet/pull/2033[#2033]

[[bc-41]]
=== Breaking Changes

* [integration] Replaced `Supplier<Schema>` with just `Schema`.
https://github.com/hazelcast/hazelcast-jet/pull/2005[#2005]
* [integration] Reordered the parameters in the JMS source so that
the `lambda` comes last.
https://github.com/hazelcast/hazelcast-jet/pull/2062[#2062]
* [jet-cli] Changed the smart routing (connecting to all cluster members)
default to `disabled`.
https://github.com/hazelcast/hazelcast-jet/pull/2104[#2104]
* [pipeline-api] Reduced the default number of concurrent service
calls per processor for `xUsingServiceAsync` transforms. It was 256; it is 4 now.
https://github.com/hazelcast/hazelcast-jet/pull/2204[#2204]